# -*- coding: utf-8 -*-
"""TopDeck: Magic The Gathering portfolio project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1k33LCnfJCdz25w45B9CdqX4ULeUR0aRI

title: This project is focused on playing cards from the popular card game (my favorite card game), Magic: THe gathering. In the analysis, we will look thru the many different cards, and explore their patterns. The reason for this is because I believe that their may be a correlation to the type of card presented, and what one it, to who drew it. Also from this project i plan to see if certain card type are almost pre-determined to be a certain color, (i.e., elf for green, red for gobbo)

Step 1: get data
"""

# prompt: mount my google drive

from google.colab import drive
drive.mount('/content/drive')

"""Import statements"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

#ML sklearn?

"""import csv"""

#create path for data
path = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/carrer/all_mtg_cards.csv')
all_mtg_cards = pd.DataFrame(path)
all_mtg_cards.head()

# remove duplicates by name
all_mtg_cards = all_mtg_cards.drop_duplicates(subset=['name'])
all_mtg_cards.head()

"""Exploration of data for analysis

"""

# top 25 most popular artists: (ones who have their name on many cards)
all_mtg_cards.groupby(['artist']).count().sort_values(by="name", ascending=False)["name"].head(25)

#color count; most frequent color_identity
all_mtg_cards.groupby(['color_identity']).count().sort_values(by="name", ascending=False)["name"].head(35)

# card type; most frequent
all_mtg_cards.groupby(['type']).count().sort_values(by="name", ascending=False)["name"].head(25)

#exploring subtypes
all_mtg_cards.groupby(['subtypes']).count().sort_values(by="name", ascending=False)["name"].head(25)

"""# next steps, get rid of nulls and high cardinalities"""

isnull = all_mtg_cards.isnull().sum()
isnull

#check the amount of rows
all_mtg_cards.shape

#fill in missing values with the mean

# drop
all_mtg_cards = all_mtg_cards.drop(columns=['names', 'colors','supertypes', 'foreign_names','printings', 'id', 'source', 'border' ,'hand', 'timeshifted', 'life', 'reserved', 'release_date', 'starter', 'rulings', 'foreign_names', 'image_url', 'legalities'])
all_mtg_cards.head()

#check for the column names
all_mtg_cards.columns

# check for nulls
all_mtg_cards.isnull().sum()



"""prooly should put all your cleaning in a wrangle function, for readability"""